// Generated by https://quicktype.io

export interface ResultOrgano {
  ok:   boolean;
  msg:  string;
  resp: Resp[];
}

export interface Resp {
  ids:  number;
  id:      number;
  nombre:  string;
  sigla:   string;
  id_sede: number;
  estado:  number;
  Sede:    Sede;
}

export interface Sede {
  id:     number;
  nombre: string;
  estado: number;
}
